// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGeNG63YJdG3TNeYWCUEDaSz0d-v1jHyA',
    appId: '1:728013780297:web:c41f59be43093ae0351698',
    messagingSenderId: '728013780297',
    projectId: 'listy-42907',
    authDomain: 'listy-42907.firebaseapp.com',
    storageBucket: 'listy-42907.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiCt3Ag7Fv8mN32A_EEjUuJEltWZHQo6E',
    appId: '1:728013780297:android:0a16e207eb384a9a351698',
    messagingSenderId: '728013780297',
    projectId: 'listy-42907',
    storageBucket: 'listy-42907.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSJkbzOB4phx6pCO5BMqMUudoevq05dBw',
    appId: '1:728013780297:ios:dd45bda5dd7b5d9d351698',
    messagingSenderId: '728013780297',
    projectId: 'listy-42907',
    storageBucket: 'listy-42907.firebasestorage.app',
    iosBundleId: 'com.example.listy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSJkbzOB4phx6pCO5BMqMUudoevq05dBw',
    appId: '1:728013780297:ios:dd45bda5dd7b5d9d351698',
    messagingSenderId: '728013780297',
    projectId: 'listy-42907',
    storageBucket: 'listy-42907.firebasestorage.app',
    iosBundleId: 'com.example.listy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGeNG63YJdG3TNeYWCUEDaSz0d-v1jHyA',
    appId: '1:728013780297:web:a035adf9264f52fc351698',
    messagingSenderId: '728013780297',
    projectId: 'listy-42907',
    authDomain: 'listy-42907.firebaseapp.com',
    storageBucket: 'listy-42907.firebasestorage.app',
  );
}
